target_path:
   path: /
   controller: App\Controller\PageController::index
   
register:
   path: /register
   controller: App\Controller\RegistrationController::register
app_login:
   path: /login
   controller: App\Controller\SecurityController::login
   methods: [GET,POST]

app_logout:
   path: /logout
   controller: App\Controller\SecurityController::logOut

user_list:
   path: /userlist
   controller: App\Controller\PageController::userList
   methods: GET

video_list:
   path: /videolist
   controller: App\Controller\PageController::videoList
   methods: GET

fetch_video_list:
   path: /fetchvideolist
   controller: App\Controller\PageController::fetchVideoList
   methods: GET

add_video:
   path: /addvideo
   controller: App\Controller\PageController::addVideo

add_category:
   path: /addcategory
   controller: App\Controller\PageController::addCategory

delete_user:
   path: /deleteuser/{id}
   controller: App\Controller\PageController::deleteUser
   methods: [GET,DELETE]

delete_category:
   path: /deletecategory/{id}
   controller: App\Controller\PageController::deleteCategory
   methods: [GET,DELETE]
   
delete_video:
   path: /deletevideo/{id}
   controller: App\Controller\PageController::deleteVideo
   methods: [GET,DELETE]

   # video_download:
   #  path: /videos/{filename}
   #  controller: App\Controller\VideoController::download