App\Entity\Video:
  type: entity
  table: videos  # The name of the database table
  manyToOne:
          category:
              targetEntity: App\Entity\Category
              inversedBy: videos
              joinColumn:
                  nullable: false
  fields:
    id:
      type: integer
      id: true

    category_name:
      type: text
      nullable: false

    createdAt:
      type: datetime
      nullable: true

  lifecycleCallbacks:
    prePersist: [ setCreatedAt ]

  repositoryClass: App\Repository\PostRepository